import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";
import { Suspense } from "react";
import Spinner from "@/components/spinner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">

      <body className={inter.className}>
        <Suspense fallback={<Spinner />}>
          <ReduxProvider>{children}</ReduxProvider>
        </Suspense>
      </body>

    </html>
  );
}
